name: "PlayFriendsPlugin"
version: "0.11.3"
author: "Jochem Kuijpers"
main: "playfriends.mc.plugin.Main"
api-version: "1.19"
commands:
  perf:
    description: "Check the server's performance."
    usage: "/perf"
depend: [CommandAPI]
